// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwmrriurtatfmvsyciry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3bXJyaXVydGF0Zm12c3ljaXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDEwMTksImV4cCI6MjA2NjQxNzAxOX0.b0gHEtmPsVwpTxFaw29w7kRJFufzRZN_K5RNP1r_D1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);